### PR TITLE
Sessions view is complete

### PR DESCRIPTION
**Pull request by snholmes**

### CODE REVIEW

**Review by ChaidGPT — DISMISSED** [review]
Everything looks to be working as intended!

**Review by ParkerW98 — DISMISSED** [review]
This looks good Shelby!

**Review by tylerjacobwilson — DISMISSED** [review]

**Review by ChaidGPT — APPROVED** [review]
Approved!!

**Review by darthcod3r — APPROVED** [review]
Excellent work :)

**Review by ParkerW98 — APPROVED** [review]
Looks great!

**Pull request merged**
