### PR TITLE
Added nav styling with logo

### PR DESCRIPTION
**Pull request by ParkerW98**
Added the logo to the nav and a background color matching our mockups.

### CODE REVIEW

**Review by darthcod3r — DISMISSED** [review]
Excellent nav bar Parker, now get me some photos of Spiderman!

**Review by snholmes — CHANGES_REQUESTED** [review]
Looks great. Would you be able to change the nav links to match the figma mockups? Eg. interviews would be "sessions" and there should be a "questions" link too.

**Review by snholmes — DISMISSED** [review]
Nice work.

**Review by tylerjacobwilson — DISMISSED** [review]

**Comment by tylerjacobwilson** [comment]
Looks good.

**Review by darthcod3r — DISMISSED** [review]
Look great!

**Review by snholmes — DISMISSED** [review]

**Review by ChaidGPT — DISMISSED** [review]
Looking good!

**Review by ChaidGPT — APPROVED** [review]
I accept

**Review by tylerjacobwilson — APPROVED** [review]

**Review by snholmes — APPROVED** [review]
Great work!

**Review by darthcod3r — APPROVED** [review]
U rock

**Pull request merged**
